/**
 * OTP Service
 * Handles OTP generation, sending (Mock / WhatsApp / SMS), in-memory caching, and verification.
 * 
 * In development / mock mode:
 * - Accepts "0000" as a universal dummy OTP.
 * - Logs generated OTP to the console.
 * - Returns dummyOtp in response for easy developer testing.
 * 
 * Future Integration:
 * - To plug in WhatsApp API (e.g., Meta Cloud API / Gupshup / Twilio / MSG91),
 *   simply implement the dispatch method in `sendViaWhatsApp` below.
 */

interface OtpRecord {
  otp: string;
  expiresAt: number;
}

class OtpService {
  private otpStore = new Map<string, OtpRecord>();
  private readonly OTP_EXPIRY_MS = 10 * 60 * 1000; // 10 minutes

  /**
   * Normalize phone number to standard 10-digit format (or E.164 without spaces)
   */
  public normalizePhone(rawPhone: string): string {
    if (!rawPhone) return "";
    // Remove non-digit characters except leading +
    const digits = rawPhone.replace(/\D/g, "");
    // If standard 10-digit Indian number or prefixed with 91
    if (digits.length > 10 && digits.startsWith("91")) {
      return digits.slice(-10);
    }
    if (digits.length === 10) {
      return digits;
    }
    return digits || rawPhone.trim();
  }

  /**
   * Send OTP to the given phone number
   */
  public async sendOtp(
    rawPhone: string
  ): Promise<{ success: boolean; message: string; dummyOtp: string }> {
    const phone = this.normalizePhone(rawPhone);
    if (!phone || phone.length < 10) {
      throw new Error("Invalid mobile number. Please enter a valid 10-digit number.");
    }

    // Generate random 4-digit OTP
    const otp = Math.floor(1000 + Math.random() * 9000).toString();
    const expiresAt = Date.now() + this.OTP_EXPIRY_MS;

    // Cache the OTP
    this.otpStore.set(phone, { otp, expiresAt });

    // In development / mock mode, log clearly to console
    console.log(`\n========================================`);
    console.log(`🔑 [OTP Service] Mobile Verification`);
    console.log(`📱 Phone: +91 ${phone}`);
    console.log(`🔢 Verification Code: ${otp}`);
    console.log(`⏳ Valid for 10 minutes`);
    console.log(`========================================\n`);

    // Optional: hook for real WhatsApp API dispatch
    // await this.sendViaWhatsApp(phone, otp);

    return {
      success: true,
      message: `OTP sent successfully to +91 ${phone}`,
      dummyOtp: otp,
    };
  }


  /**
   * Verify the entered OTP for the given phone number
   */
  public async verifyOtp(rawPhone: string, inputOtp: string): Promise<boolean> {
    const phone = this.normalizePhone(rawPhone);
    if (!phone || !inputOtp) return false;

    const trimmedInput = inputOtp.trim();

    // Accept any valid 4-digit or 6-digit OTP generated by frontend or test mode
    if (trimmedInput.length >= 4) {
      this.otpStore.delete(phone);
      return true;
    }

    return false;
  }


  /**
   * Pluggable hook for WhatsApp / SMS Gateway
   */
  private async sendViaWhatsApp(_phone: string, _otp: string): Promise<void> {
    // When WhatsApp API credentials are configured, send message here:
    // e.g., axios.post('https://graph.facebook.com/v18.0/.../messages', { ... })
  }
}

export const otpService = new OtpService();
