export const studentSurveySchema = {
  slug: "student-skills-survey",
  title: "Undergraduate Student Skills & Career Survey 🎓",
  description:
    "Unisole Skill AI Labs is surveying college students across Himachal Pradesh in support of initiatives with the Government of Himachal Pradesh to implement the National Education Policy (NEP) and design meaningful, credit-linked industrial courses at the undergraduate level. Your authentic feedback will directly help shape upcoming practical training curriculums.",
  sections: [
    {
      id: "student_profile",
      title: "Your Academic Profile",
      description: "Basic educational background and institution details.",
      questions: [
        {
          id: "student_name",
          title: "Full Name",
          type: "text",
          required: true,
        },
        {
          id: "student_phone",
          title: "Mobile Number",
          type: "text",
          required: true,
        },
        {
          id: "student_college",
          title: "College / Institution Name",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "Rajkiya Kanya Mahavidyalaya (RKMV), Shimla",
            "Centre of Excellence Government College, Sanjauli",
            "Rajiv Gandhi Government Degree College, Kotshera",
            "Government College, Dharamshala",
            "Government College, Mandi",
            "Government College, Solan",
            "Government College, Hamirpur",
            "Government College, Bilaspur",
            "Government College, Kullu",
            "Government College, Una",
            "Government College, Chamba",
            "Himachal Pradesh University (HPU), Shimla",
          ],
        },
        {
          id: "student_stream",
          title: "Current Course / Degree Stream",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "BCA (Bachelor of Computer Applications)",
            "B.Sc Computer Science / IT",
            "B.Tech / B.E. (Engineering)",
            "MCA (Master of Computer Applications)",
            "B.Com (Commerce)",
            "BBA / Management",
            "B.Sc (General Sciences)",
            "B.A. (Arts / Humanities)",
          ],
        },
        {
          id: "student_year",
          title: "Which year are you currently studying in?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: ["1st Year", "2nd Year", "3rd Year", "Final Year / 4th Year"],
        },
      ],
    },
    {
      id: "college_reality",
      title: "College Realities & Career Perspective",
      description: "Your honest input on college challenges, guidance, and career direction.",
      questions: [
        {
          id: "current_focus",
          title: "Right now, what are you mainly focusing on alongside your college studies?",
          type: "single-select",
          required: true,
          options: [
            "Preparing for private / tech industry jobs & placements",
            "Preparing for government exams (Civil Services, Banking, Defense, etc.)",
            "Enrolled in an external skill course or certification",
            "Working on personal projects, coding, or freelancing",
            "Focusing strictly on regular college exams and syllabus",
            "Nothing specific right now / still exploring options",
          ],
        },
        {
          id: "current_focus_reason",
          title: "Was this your own choice or did someone suggest it? (If your own choice, why?)",
          type: "text",
          required: false,
        },
        {
          id: "career_ambition",
          title: "What is your primary career ambition right now?",
          type: "single-select",
          required: true,
          options: [
            "Private sector job (Software / Tech / Corporate)",
            "Government job / Competitive exam",
            "Higher studies (Master’s, MCA, M.Tech, MBA, Ph.D.)",
            "Starting a business / Startup / Entrepreneurship",
            "Freelancing / Remote global client work",
            "Still undecided / Exploring different careers",
          ],
        },
        {
          id: "ambition_preparation",
          title: "What are you currently doing to prepare for this ambition?",
          type: "text",
          required: false,
        },
        {
          id: "college_problem",
          title: "What feels like the biggest problem or bottleneck at the college level?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "Outdated syllabus that does not match modern industry requirements",
            "Lack of hands-on computer labs, practical projects, and coding exposure",
            "Very few or no campus placement and internship opportunities",
            "Too much focus on memorization and exams instead of real skill building",
            "Lack of career mentorship from experienced industry professionals",
          ],
        },
        {
          id: "system_problem",
          title: "In your honest opinion, what is the biggest problem in the overall education system?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "College degrees no longer guarantee jobs or practical capability",
            "Huge gap between theoretical classroom teaching and corporate hiring standards",
            "Students are taught for marks, not for critical thinking or problem solving",
            "Emerging fields (AI, Machine Learning, Data) are not integrated early enough",
            "Career guidance starts too late (usually only in final year)",
          ],
        },
        {
          id: "past_course_exp",
          title: "Have you previously taken any offline or online courses?",
          type: "single-select",
          required: true,
          options: [
            "Yes, offline training / coaching institute",
            "Yes, online platforms (Udemy, Coursera, YouTube, etc.)",
            "Yes, both online and offline programs",
            "No, I have never taken an external course",
          ],
        },
        {
          id: "past_course_feedback",
          title: "If yes, what was good about it, and what was disappointing or missing?",
          type: "text",
          required: false,
        },
        {
          id: "course_motivation",
          title: "What is your main reason for enrolling in a skill course?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "To acquire practical, job-ready skills",
            "To get a verified certificate for my resume",
            "Genuine personal curiosity and interest in technology",
            "College / internship mandatory requirement",
            "To build real projects for my GitHub / portfolio",
          ],
        },
        {
          id: "seniors_guidance",
          title: "Do you get useful career guidance from college seniors, or do they seem just as confused?",
          type: "single-select",
          required: true,
          options: [
            "Yes, seniors provide clear, practical guidance on careers and skills",
            "Somewhat, but most seniors are equally confused about what to do next",
            "No, there is almost no interaction or guidance from seniors",
            "Seniors mostly only advise preparing for government exams",
          ],
        },
        {
          id: "professors_direction",
          title: "Which direction do college professors usually encourage or push students towards?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "Preparing for government jobs / civil service exams",
            "Pursuing higher studies (Master’s, MCA, M.Tech, MBA)",
            "Private sector / IT / Corporate jobs",
            "They mostly focus only on syllabus and exams, rarely discussing careers",
          ],
        },
        {
          id: "parents_expectation",
          title: "What career path do your parents want for you, and does it match your own choice?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "Parents want a government job — and that matches my personal ambition",
            "Parents want a government job — but I prefer private sector / tech / business",
            "Parents want a private / tech career — and that matches my choice",
            "Parents fully support whatever career path I choose for myself",
          ],
        },
        {
          id: "sector_preference",
          title: "What is your honest opinion when comparing the Private Sector vs Government Sector?",
          type: "single-select",
          required: true,
          options: [
            "Prefer Private Sector (Faster career growth, merit-based, higher salary upside)",
            "Prefer Government Sector (Long-term job security, pension/benefits, work-life balance)",
            "Open to both — whichever offers a solid and genuine starting opportunity",
            "Prefer starting my own business / Entrepreneurship / Freelancing",
          ],
        },
      ],
    },
    {
      id: "nep_skill_design",
      title: "Designing Your Ideal Skill Program (NEP)",
      description: "Tell us how government-recognized skill courses should be crafted.",
      questions: [
        {
          id: "interested_skills",
          title: "Which skill programs would you be most interested in taking?",
          type: "multi-select",
          hasOther: true,
          required: true,
          options: [
            "Data Science",
            "Data Analytics",
            "Machine Learning",
            "Generative AI & AI Tools",
            "Full Stack Data Science",
            "Entrepreneurship & Startup Building",
            "Cyber Security & Ethical Hacking",
            "Data Engineering",
          ],
        },
        {
          id: "learning_mode",
          title: "Which learning format do you prefer?",
          type: "single-select",
          required: true,
          options: [
            "Offline (In-person classes and hands-on computer labs)",
            "Online (Live online sessions + recorded learning materials)",
            "Hybrid (Online sessions + regular weekend in-person workshops)",
          ],
        },
        {
          id: "degree_skill_weightage",
          title: "How should a student's time and effort ideally be divided between the college degree and practical skill training?",
          type: "single-select",
          required: true,
          options: [
            "50% Degree + 50% Practical Skill Training (Equal balance)",
            "30% Degree + 70% Practical Skill Training (Heavy emphasis on practical skills)",
            "70% Degree + 30% Practical Skill Training (College degree as main priority)",
            "100% Practical Skill Training & Projects",
          ],
        },
        {
          id: "credit_value",
          title: "If this skill training is officially counted towards your college degree as Academic Credits (under NEP), would that make it more valuable to you?",
          type: "single-select",
          required: true,
          options: [
            "Yes! Official academic credits in my degree would make it significantly more valuable",
            "A separate recognized industry certificate is already enough for me",
            "Both official credits and industry certificates are equally important",
            "Not sure / Depends on course quality and university recognition",
          ],
        },
        {
          id: "budget_preference",
          title: "For a genuinely high-quality 3-month skill program with live mentorship and projects, what could you realistically afford to pay?",
          type: "single-select",
          required: true,
          options: [
            "Only if it is 100% free or fully government-subsidized",
            "₹1,000 – ₹2,500 for the entire 3 months",
            "₹2,500 – ₹5,000 for the entire 3 months",
            "₹5,000+ if it directly includes assured internship or placement support",
          ],
        },
        {
          id: "weekly_hours",
          title: "Alongside your regular college studies, how many hours per week can you realistically dedicate to skill training?",
          type: "single-select",
          required: true,
          options: [
            "3–5 hours per week (around 30–45 minutes daily)",
            "6–10 hours per week (around 1–1.5 hours daily)",
            "10–15 hours per week (regular practice + weekends)",
            "15+ hours per week (intensive commitment)",
          ],
        },
      ],
    },
  ],
};
