export const studentSurveySchema = {
  slug: "student-skills-survey",
  title: "Undergraduate Student Skills & Career Survey 🎓",
  description:
    "Unisole Skill AI Labs is surveying college students across Himachal Pradesh in support of initiatives with the Government of Himachal Pradesh to implement the National Education Policy (NEP) and design meaningful, credit-linked industrial courses at the undergraduate level. Your authentic feedback will directly help shape upcoming practical training curriculums.",
  sections: [
    {
      id: "student_profile",
      title: "Your Academic Profile",
      description: "Basic educational background and institution details.",
      questions: [
        {
          id: "student_name",
          title: "Full Name",
          type: "text",
          required: true,
        },
        {
          id: "student_phone",
          title: "Mobile Number",
          type: "text",
          required: true,
        },
        {
          id: "student_college",
          title: "College / Institution Name",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "Rajkiya Kanya Mahavidyalaya (RKMV), Shimla",
            "Centre of Excellence Government College, Sanjauli",
            "Rajiv Gandhi Government Degree College, Kotshera",
            "Government College, Dharamshala",
            "Government College, Mandi",
            "Government College, Solan",
            "Government College, Hamirpur",
            "Government College, Bilaspur",
            "Government College, Kullu",
            "Government College, Una",
            "Government College, Chamba",
            "Himachal Pradesh University (HPU), Shimla",
          ],
        },
        {
          id: "student_stream",
          title: "Current Course / Degree Stream",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "BCA (Bachelor of Computer Applications)",
            "B.Sc Computer Science / IT",
            "B.Tech / B.E. (Engineering)",
            "MCA (Master of Computer Applications)",
            "B.Com (Commerce)",
            "BBA / Management",
            "B.Sc (General Sciences)",
            "B.A. (Arts / Humanities)",
          ],
        },
        {
          id: "student_year",
          title: "Which year are you currently studying in?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: ["1st Year", "2nd Year", "3rd Year", "Final Year / 4th Year"],
        },
      ],
    },
    {
      id: "college_reality",
      title: "College Realities & Career Perspective",
      description: "Your honest input on college challenges, guidance, and career direction.",
      questions: [
        {
          id: "current_focus",
          title: "Abhi aap kya kar rahe ho — job ki taiyari, koi course, ya kuch specific nahi?",
          type: "single-select",
          required: true,
          options: [
            "Preparing for private / tech industry jobs & placements",
            "Preparing for government exams (Civil Services, Banking, Defense, etc.)",
            "Enrolled in an external skill course or certification",
            "Working on personal projects, coding, or freelancing",
            "Focusing strictly on regular college exams and syllabus",
            "Nothing specific right now / still exploring options",
          ],
        },
        {
          id: "current_focus_reason",
          title: "Yeh khud ki choice thi ya kisi ne suggest kiya? (agar khud ki choice thi, toh kyun?)",
          type: "text",
          required: false,
        },
        {
          id: "career_ambition",
          title: "Current ambition kya hai — job, higher study, business, ya govt exam?",
          type: "single-select",
          required: true,
          options: [
            "Private sector job (Software / Tech / Corporate)",
            "Government job / Competitive exam",
            "Higher studies (Master’s, MCA, M.Tech, MBA, Ph.D.)",
            "Starting a business / Startup / Entrepreneurship",
            "Freelancing / Remote global client work",
            "Still undecided / Exploring different careers",
          ],
        },
        {
          id: "ambition_preparation",
          title: "Uske liye abhi kya kar rahe ho?",
          type: "text",
          required: false,
        },
        {
          id: "college_problem",
          title: "College level pe sabse badi problem kya lagti hai?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "Outdated syllabus that does not match modern industry requirements",
            "Lack of hands-on computer labs, practical projects, and coding exposure",
            "Very few or no campus placement and internship opportunities",
            "Too much focus on memorization and exams instead of real skill building",
            "Lack of career mentorship from experienced industry professionals",
          ],
        },
        {
          id: "system_problem",
          title: "Poore education system mein sabse badi problem kya lagti hai?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "College degrees no longer guarantee jobs or practical capability",
            "Huge gap between theoretical classroom teaching and corporate hiring standards",
            "Students are taught for marks, not for critical thinking or problem solving",
            "Emerging fields (AI, Machine Learning, Data) are not integrated early enough",
            "Career guidance starts too late (usually only in final year)",
          ],
        },
        {
          id: "past_course_exp",
          title: "Pehle koi offline/online course kiya hai?",
          type: "single-select",
          required: true,
          options: [
            "Yes, offline training / coaching institute",
            "Yes, online platforms (Udemy, Coursera, YouTube, etc.)",
            "Yes, both online and offline programs",
            "No, I have never taken an external course",
          ],
        },
        {
          id: "past_course_feedback",
          title: "Kya achha tha, kya nahi?",
          type: "text",
          required: false,
        },
        {
          id: "course_motivation",
          title: "Course lene ka main reason kya hota hai — certification, job-skill, ya apni interest?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "To acquire practical, job-ready skills (Job-skill)",
            "To get a verified certificate for my resume (Certification)",
            "Genuine personal curiosity and interest in technology (Apni interest)",
            "College / internship mandatory requirement",
            "To build real projects for my GitHub / portfolio",
          ],
        },
        {
          id: "seniors_guidance",
          title: "Seniors se sahi guidance milti hai, ya woh bhi confused hote hain?",
          type: "single-select",
          required: true,
          options: [
            "Yes, seniors provide clear, practical guidance on careers and skills",
            "Somewhat, but most seniors are equally confused about what to do next",
            "No, there is almost no interaction or guidance from seniors",
            "Seniors mostly only advise preparing for government exams",
          ],
        },
        {
          id: "professors_direction",
          title: "Professors kis taraf push karte hain — higher study, govt job, ya private job?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "Higher studies (Master’s, MCA, M.Tech, MBA)",
            "Government jobs / Civil service exams",
            "Private sector / IT / Corporate jobs",
            "They mostly focus only on syllabus and exams, rarely discussing careers",
          ],
        },
        {
          id: "parents_expectation",
          title: "Parents kya chahte hain, aur kya woh aapki apni pasand se match karta hai?",
          type: "single-select",
          hasOther: true,
          required: true,
          options: [
            "Parents want a government job — and that matches my personal ambition",
            "Parents want a government job — but I prefer private sector / tech / business",
            "Parents want a private / tech career — and that matches my choice",
            "Parents fully support whatever career path I choose for myself",
          ],
        },
        {
          id: "sector_preference",
          title: "Private sector vs government sector — honest opinion?",
          type: "single-select",
          required: true,
          options: [
            "Prefer Private Sector (Faster career growth, merit-based, higher salary upside)",
            "Prefer Government Sector (Long-term job security, pension/benefits, work-life balance)",
            "Open to both — whichever offers a solid and genuine starting opportunity",
            "Prefer starting my own business / Entrepreneurship / Freelancing",
          ],
        },
      ],
    },
    {
      id: "nep_skill_design",
      title: "Designing Your Ideal Skill Program (NEP)",
      description: "Tell us how government-recognized skill courses should be crafted.",
      questions: [
        {
          id: "interested_skills",
          title: "Skill program mein sabse zyada interest kis mein hoga?",
          type: "multi-select",
          hasOther: true,
          required: true,
          options: [
            "Data Science",
            "Data Analytics",
            "Machine Learning",
            "Generative AI",
            "Full Stack Data Science",
            "Entrepreneurship",
            "Cyber Security",
            "Data Engineering",
            "Finance",
          ],
        },
        {
          id: "learning_mode",
          title: "Offline, online, ya hybrid — kya prefer karoge?",
          type: "single-select",
          required: true,
          options: [
            "Offline (In-person classes and hands-on computer labs)",
            "Online (Live online sessions + recorded learning materials)",
            "Hybrid (Online sessions + regular weekend in-person workshops)",
          ],
        },
        {
          id: "degree_skill_weightage",
          title: "Core degree aur skill training ko kitna weightage dena chahiye?",
          type: "single-select",
          required: true,
          options: [
            "50% Degree + 50% Practical Skill Training (Equal balance)",
            "30% Degree + 70% Practical Skill Training (Heavy emphasis on practical skills)",
            "70% Degree + 30% Practical Skill Training (College degree as main priority)",
            "100% Practical Skill Training & Projects",
          ],
        },
        {
          id: "credit_value",
          title: "Agar yeh skill training aapki degree mein official academic credit ke roop mein count ho sake, toh kya woh zyada valuable lagega — ya ek separate certificate kaafi hai?",
          type: "single-select",
          required: true,
          options: [
            "Yes! Official academic credits in my degree would make it significantly more valuable",
            "A separate recognized industry certificate is already enough for me",
            "Both official credits and industry certificates are equally important",
            "Not sure / Depends on course quality and university recognition",
          ],
        },
        {
          id: "budget_preference",
          title: "Ek genuinely accha 3-month skill program ke liye aap kitna realistically pay kar sakte ho — ya sirf tab lenge jab woh free/govt-subsidized ho?",
          type: "single-select",
          required: true,
          options: [
            "Only if it is 100% free or fully government-subsidized",
            "₹1,000 – ₹2,500 for the entire 3 months",
            "₹2,500 – ₹5,000 for the entire 3 months",
            "₹5,000+ if it directly includes assured internship or placement support",
          ],
        },
        {
          id: "weekly_hours",
          title: "Weekly kitne ghante nikal sakte ho aisi training ke liye, apni regular padhai ke saath?",
          type: "single-select",
          required: true,
          options: [
            "3–5 hours per week (around 30–45 minutes daily)",
            "6–10 hours per week (around 1–1.5 hours daily)",
            "10–15 hours per week (regular practice + weekends)",
            "15+ hours per week (intensive commitment)",
          ],
        },
        {
          id: "has_laptop",
          title: "laptop hai ??",
          type: "single-select",
          required: true,
          options: [
            "Yes, I have my own personal laptop / PC",
            "No, but I have regular access to college computer labs or a shared laptop",
            "No, I currently only have a smartphone",
          ],
        },
        {
          id: "join_ai_network",
          title: "would you like to join the national AI network of unisole",
          type: "single-select",
          required: true,
          options: [
            "Yes! I want to join the Unisole National AI Network & receive community invites",
            "Maybe later / Still exploring options",
          ],
        },
      ],
    },
  ],
};
