export const studentSurveySchema = {
  slug: "student-skills-survey",
  title: "Student Skills & Career Aspirations Survey 🎓",
  description:
    "A quick snapshot of where you are, where you want to go, and what skills can help you get there. Your responses will help us shape high-impact, industry-relevant learning opportunities tailored for you.",
  sections: [
    {
      id: "career_vision",
      title: "Your Goals & Learning Needs 🚀",
      description: "Tell us about what you want to achieve and what's holding you back.",
      questions: [
        {
          id: "aiming_for",
          title: "What are you currently aiming for?",
          subtitle: "Select all fields you are passionate about exploring",
          type: "multi-select",
          required: true,
          options: [
            "💻 Software Development / IT Career",
            "🤖 AI / Machine Learning Career",
            "📊 Data Science / Data Analytics",
            "🔐 Cybersecurity / Cloud / IT Infrastructure",
            "💼 Business / Entrepreneurship / Startup",
            "📈 Finance / Accounting / Commerce Career",
            "📣 Digital Marketing / Content Creation",
            "🎓 Higher Studies / Further Education",
          ],
        },
        {
          id: "why_learn",
          title: "Why do you want to learn new skills?",
          subtitle: "What is your primary driving motivation?",
          type: "multi-select",
          required: true,
          options: [
            "Improve job opportunities",
            "Prepare for internships",
            "Build real-world projects",
            "Freelancing / Earning",
            "Start a business / Startup",
            "Academic knowledge",
            "Explore a new field",
            "Keep up with emerging technology",
            "Personal interest",
          ],
        },
        {
          id: "challenges",
          title: "What challenges are you currently facing when trying to learn new skills?",
          type: "multi-select",
          required: true,
          options: [
            "Lack of time",
            "Course fees",
            "Don't know where to start",
            "Lack of proper guidance",
            "College workload",
            "Don't know which skills are useful for my career",
            "Lack of practical learning opportunities",
            "Lack of access to tools/resources",
            "Difficulty staying consistent",
          ],
        },
        {
          id: "course_factors",
          title: "According to you, what factors make a course truly valuable?",
          type: "multi-select",
          required: true,
          options: [
            "Practical, hands-on learning",
            "Real-world projects",
            "Industry-relevant skills",
            "Internship opportunity",
            "Mentorship from professionals",
            "Portfolio / GitHub projects",
            "Certificate",
            "Flexible timings",
            "Affordable fees",
            "Access to AI tools & software",
            "Beginner-friendly teaching",
          ],
        },
        {
          id: "laptop_access",
          title: "Do you currently have access to a laptop or computer for learning?",
          type: "single-select",
          required: true,
          options: [
            "Yes, I have my own laptop/computer",
            "Yes, but I share it with someone",
            "No, I don't currently have access to one",
            "I can access one when needed (college/lab/library, etc.)",
          ],
        },
      ],
    },
    {
      id: "stream_skills",
      title: "Explore Your Skills & Courses 💡",
      description: "Pick your academic stream to unlock tailored curriculum choices.",
      questions: [
        {
          id: "stream",
          title: "What is your current course / stream?",
          type: "single-select",
          required: true,
          options: [
            "BCA",
            "MCA",
            "B.Com",
            "B.Sc",
            "B.Sc. CS",
            "B.A.",
            "BBA / Management",
            "Other",
          ],
        },
        {
          id: "skills_bca",
          title: "Which of the following courses/skills would you be interested in learning? (BCA)",
          type: "multi-select",
          required: false,
          condition: { field: "stream", operator: "eq", value: "BCA" },
          options: [
            "Web Development — HTML, CSS & JavaScript",
            "Full-Stack Development",
            "Python Programming",
            "Java Programming",
            "App Development",
            "DSA & Problem Solving",
            "Artificial Intelligence & Machine Learning",
            "Generative AI & AI Tools",
            "Data Science",
            "Data Analytics & Visualization",
            "Cybersecurity & Ethical Hacking",
            "Cloud Computing & DevOps",
            "Database & SQL",
            "Software Testing & Automation",
          ],
        },
        {
          id: "skills_mca",
          title: "Which of the following courses/skills would you be interested in learning? (MCA)",
          type: "multi-select",
          required: false,
          condition: { field: "stream", operator: "eq", value: "MCA" },
          options: [
            "Full-Stack Development",
            "Web Development — HTML, CSS & JavaScript",
            "Python Programming",
            "Java Programming",
            "DSA & Problem Solving",
            "Artificial Intelligence & Machine Learning",
            "Generative AI & AI Tools",
            "Data Science",
            "Data Analytics & Visualization",
            "Cloud Computing & DevOps",
            "Cybersecurity & Ethical Hacking",
            "Database & SQL",
            "App Development",
            "Git & GitHub / Version Control",
          ],
        },
        {
          id: "skills_bcom",
          title: "Which of the following courses/skills would you be interested in learning? (B.Com)",
          type: "multi-select",
          required: false,
          condition: { field: "stream", operator: "eq", value: "B.Com" },
          options: [
            "Tally Prime & Accounting",
            "Excel & Advanced Excel",
            "Financial Analytics",
            "Data Analytics & Visualization",
            "AI for Business & Commerce",
            "Generative AI & AI Tools",
            "Digital Marketing",
            "AI Applications & Automation",
          ],
        },
        {
          id: "skills_bsc",
          title: "Which of the following courses/skills would you be interested in learning? (B.Sc)",
          type: "multi-select",
          required: false,
          condition: { field: "stream", operator: "eq", value: "B.Sc" },
          options: [
            "Python Programming",
            "Artificial Intelligence & Machine Learning",
            "Data Science",
            "Data Analytics & Visualization",
            "Generative AI & AI Tools",
            "Database & SQL",
            "Web Development",
            "Cybersecurity & Ethical Hacking",
            "Cloud Computing & DevOps",
          ],
        },
        {
          id: "skills_bsc_cs",
          title: "Which of the following courses/skills would you be interested in learning? (B.Sc CS)",
          type: "multi-select",
          required: false,
          condition: { field: "stream", operator: "eq", value: "B.Sc. CS" },
          options: [
            "Web Development — HTML, CSS & JavaScript",
            "Full-Stack Development",
            "Python Programming",
            "Java Programming",
            "DSA & Problem Solving",
            "Artificial Intelligence & Machine Learning",
            "Generative AI & AI Tools",
            "Data Science",
            "Data Analytics & Visualization",
            "Cloud Computing & DevOps",
            "Cybersecurity & Ethical Hacking",
            "Database & SQL",
            "App Development",
          ],
        },
        {
          id: "skills_ba",
          title: "Which of the following courses/skills would you be interested in learning? (B.A.)",
          type: "multi-select",
          required: false,
          condition: { field: "stream", operator: "eq", value: "B.A." },
          options: [
            "🧠 AI for Psychology & Behavioural Sciences",
            "🐍 Python Programming for Beginners",
            "📚 AI for Education & Teaching",
            "⚖️ AI for Law & Legal Applications",
            "🎨 AI for Media, Design & Creative Work",
            "📱 Generative AI & AI Tools for Everyday Work",
            "📣 Digital Marketing & Social Media",
            "🎬 Video Editing & Content Creation",
            "🎨 Graphic Design",
            "🖥️ UI/UX Design",
            "📊 Data Analytics & Visualization",
            "📝 AI Tools for Research & Academic Work",
          ],
        },
        {
          id: "skills_bba",
          title: "Which of the following courses/skills would you be interested in learning? (BBA / Management)",
          type: "multi-select",
          required: false,
          condition: { field: "stream", operator: "eq", value: "BBA / Management" },
          options: [
            "🤖 AI for Business & Management",
            "📊 Data Analytics for Business",
            "📈 Business Intelligence & Dashboards",
            "📣 Digital Marketing & Social Media Strategy",
            "💰 Financial Analytics & Business Finance",
            "📊 Excel & Advanced Excel for Business",
            "🧠 Business Strategy & Decision Making",
            "🚀 Startup & Entrepreneurship",
            "🛒 E-Commerce & Digital Business",
            "📱 Generative AI & AI Tools for Business",
            "🧾 Tally Prime & Accounting",
          ],
        },
        {
          id: "skills_other",
          title: "Which AI applications would you be interested in learning? (Other)",
          type: "multi-select",
          required: false,
          condition: { field: "stream", operator: "eq", value: "Other" },
          options: [
            "🧠 AI for Psychology & Behavioural Sciences",
            "🧬 AI for Life Sciences & Biotechnology",
            "🏥 AI for Healthcare & Medical Applications",
            "📚 AI for Education & Teaching",
            "⚖️ AI for Law & Legal Applications",
            "🎨 AI for Media, Design & Creative Work",
            "📱 Generative AI & AI Tools for Everyday Work",
            "🔬 AI for Research & Academic Work",
          ],
        },
        {
          id: "missed_skills",
          title: "Is there any course or skill we missed that you would genuinely like to learn?",
          type: "text",
          required: false,
          placeholder: "e.g. Rust, Robotics, Blockchain, Quantum Computing...",
        },
      ],
    },
    {
      id: "student_identity",
      title: "Where should we send your results? 🎓",
      description: "Final step! Provide your contact info so we can send your personalized roadmap and workshop invites.",
      questions: [
        {
          id: "name",
          title: "Full Name",
          type: "text",
          required: true,
          placeholder: "e.g. Priya Sharma",
        },
        {
          id: "phone",
          title: "Mobile Number",
          type: "phone",
          required: true,
          placeholder: "e.g. 9876543210",
        },
        {
          id: "college_name",
          title: "What is your institution name ?",
          type: "dropdown-or-custom",
          required: true,
          options: [
            "Rajkiya Kanya Mahavidyalaya, Shimla",
            "Centre of Excellence Government College, Sanjauli",
            "Rajiv Gandhi Government Degree College, Kotshera",
          ],
          placeholder: "Select or type your college name...",
        },
        {
          id: "year_of_study",
          title: "Which year are you currently studying in?",
          type: "single-select",
          required: true,
          options: ["1st Year", "2nd Year", "3rd Year", "Final Year"],
        },
      ],
    },
  ],
};
